# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nrf52840dongle_nrf52840
    shield: corne_dongle_nordic
    cmake-args: -DCONFIG_ZMK_KEYBOARD_NAME=\"Nice_Dongle_O\"
    artifact-name: nice_corne_dongle_oled
    snippet: studio-rpc-usb-uart
  - board: mikoto@7.2
    shield: corne_left_peripheral nice_view_adapter nice_epaper
    # snippet: studio-rpc-usb-uart
  - board: mikoto@7.2
    shield: corne_right nice_view_adapter nice_epaper
  - board: mikoto@7.2
    shield: settings_reset
